### ISSUE TITLE
Whats the command to read or send a package with a fixed payload?

### ISSUE THREAD

**Issue by LinoFel** [AndyRids/pico-nrf24#6]
Hi, I want to send and receive payloads with a fixed length of 12 bytes. I've added "my_nrf.payload_size(DATA_PIPE_0, TWELVE_BYTES);" to the initialization and added "TWELVE_BYTES" to the nrf24_driver.h. I've disabled dynamic payloads as well. Now my question is how the receiving command changes from the initial command "my_nrf.read_packet(&payload_zero, sizeof(payload_zero));" for fixed payload lengths . Do I have to change the code of the transmitter as well and is there a runtime benefit when choosing a fixed payload length? Greetings :)

**Comment by MertKalkanci** [comment]
There may can be a benefit of this technuqie while transmitting large structs or arrays but also can be some disadvantages like you may need to write an algorithm to verify packages etc. And yes it seems you need to change the code on the transmitter too.

But I reccomend you to use normal version of nrf24 driver also don't forget to make your driver code public because of GPL licence you may csn have headaches.

I hope this helps, have a good day.

**Comment by LinoFel** [comment]
Hello Mert, thanks for your reply and your help. I think I will stick to the original driver and use the standard settings since I am just experiencing a very minor data loss. 

I am really new to licenses. Is it a must to publish the driver even if it stays 100% original or just in terms of a change? 

I wish you a good day as well!

**Comment by MertKalkanci** [comment]
I think you don't have to publish it if it stays original, the thing I am talking about is called **copyleft**. you can have a quick look about it, have a great day.

**Comment by MertKalkanci** [comment]
Also if your problem is solved it would be nice to close the issue.

**Comment by LinoFel** [comment]
Thank you so much for your help and the information. Since my problem is solved I will close the issue now. Have a great day too!
